name: ESLint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install ESLint
        run: npm init @eslint/config@latest -- --config eslint-config-standard

      - name: Run ESLint
        run: npx eslint .
