name: CI for mapboxgl-remix

on:
  push:
    paths:
      - packages/mapboxgl-remix
      - package.json
      - .github/workflows/mapboxgl-remix.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint --workspace=mapboxgl-remix

      - naem: Build
        run: npm run build --workspace=mapboxgl-remix
